version: '3.8'

services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: react_client
    ports:
      - "3000:80"
    # depends_on:
    #   - server
    networks:
      - app-network
  
  webrtc:
    build:
      context: ./webrtc-test/backend 
    container_name: webrtc-server
    ports:
      - "5001:5001"
    networks:
      - app-network

  # server:
  #   build: ./server
  #   container_name: node_server
  #   ports:
  #     - "4040:4040"
  #   environment:
  #     - PORT=4040
  #     - MONGO_URL=mongodb://mongo:27017/course_platform
  #   depends_on:
  #     - mongo
  #   networks:
  #     - app-network
  # mongo:
  #   image: mongo:latest
  #   container_name: mongo_db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  #   networks:
  #     - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge